[2024-09-06T13:24:15.688+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-06T13:24:15.699+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: async_flow.exit_task manual__2024-09-06T13:23:43.549669+00:00 [queued]>
[2024-09-06T13:24:15.704+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: async_flow.exit_task manual__2024-09-06T13:23:43.549669+00:00 [queued]>
[2024-09-06T13:24:15.704+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-06T13:24:15.713+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): exit_task> on 2024-09-06 13:23:43.549669+00:00
[2024-09-06T13:24:15.717+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1266) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-06T13:24:15.718+0000] {standard_task_runner.py:72} INFO - Started process 1267 to run task
[2024-09-06T13:24:15.719+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'async_flow', 'exit_task', 'manual__2024-09-06T13:23:43.549669+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dags_async_flow.py', '--cfg-path', '/tmp/tmpm9jf9qja']
[2024-09-06T13:24:15.721+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask exit_task
[2024-09-06T13:24:15.750+0000] {task_command.py:467} INFO - Running <TaskInstance: async_flow.exit_task manual__2024-09-06T13:23:43.549669+00:00 [running]> on host d02a1db40bad
[2024-09-06T13:24:15.788+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='async_flow' AIRFLOW_CTX_TASK_ID='exit_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T13:23:43.549669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-06T13:23:43.549669+00:00'
[2024-09-06T13:24:15.789+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-06T13:24:15.795+0000] {logging_mixin.py:190} INFO - Exiting the DAG
[2024-09-06T13:24:15.796+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-06T13:24:15.802+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-06T13:24:15.802+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=async_flow, task_id=exit_task, run_id=manual__2024-09-06T13:23:43.549669+00:00, execution_date=20240906T132343, start_date=20240906T132415, end_date=20240906T132415
[2024-09-06T13:24:15.819+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-06T13:24:15.828+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-06T13:24:15.829+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
