[2024-09-06T16:30:45.350+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-06T16:30:45.357+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: async_flow.exit_task manual__2024-09-06T16:29:29.656765+00:00 [queued]>
[2024-09-06T16:30:45.361+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: async_flow.exit_task manual__2024-09-06T16:29:29.656765+00:00 [queued]>
[2024-09-06T16:30:45.361+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-09-06T16:30:45.366+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): exit_task> on 2024-09-06 16:29:29.656765+00:00
[2024-09-06T16:30:45.369+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2322) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-06T16:30:45.370+0000] {standard_task_runner.py:72} INFO - Started process 2323 to run task
[2024-09-06T16:30:45.370+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'async_flow', 'exit_task', 'manual__2024-09-06T16:29:29.656765+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/dags_async_flow.py', '--cfg-path', '/tmp/tmp4ro9t6tm']
[2024-09-06T16:30:45.371+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask exit_task
[2024-09-06T16:30:45.392+0000] {task_command.py:467} INFO - Running <TaskInstance: async_flow.exit_task manual__2024-09-06T16:29:29.656765+00:00 [running]> on host a3a5f1897683
[2024-09-06T16:30:45.427+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='async_flow' AIRFLOW_CTX_TASK_ID='exit_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-06T16:29:29.656765+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-06T16:29:29.656765+00:00'
[2024-09-06T16:30:45.427+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-06T16:30:45.434+0000] {dags_async_flow.py:117} INFO - Exiting the DAG
[2024-09-06T16:30:45.434+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-06T16:30:45.439+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-06T16:30:45.439+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=async_flow, task_id=exit_task, run_id=manual__2024-09-06T16:29:29.656765+00:00, execution_date=20240906T162929, start_date=20240906T163045, end_date=20240906T163045
[2024-09-06T16:30:45.471+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-06T16:30:45.479+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-06T16:30:45.480+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
